#!/bin/bash
#
# Copyright (c) 2019 EOS Sw/eden
#
# Simple script to view the currect version and to
# switch between versions (updating an symlink)

SOURCE_BASE=/opt/eosio.cdt
TARGET=/usr/local/eosio.cdt

# param <index>
function name_to_index() {

    local cmp=$(($1+0))
    local i=1
    for v in $(ls ${SOURCE_BASE}) ; do
       if [ $i -eq $cmp ]; then
          echo -n $v
          break
       fi
       ((i++))
    done
}

# param <version>
function set_version() {

    VERSION=$(name_to_index ${1})
    SOURCE=${SOURCE_BASE}/${VERSION}

    if [ -z "${VERSION}" ]; then
        echo -e "[\e[31mError\e[0m] Index out of range: ${1}"
        exit 1
    fi

    if [ ! -d "${SOURCE}" ]; then
        echo -e "[\e[31mError\e[0m] Could not switch to version '${VERSION}': Directory '${SOURCE}' does not exist."
        exit 1
    fi

    # Update/Create symlink.
    ln -sfn "${SOURCE}" "${TARGET}"

    if [ $? -ne 0 ]; then
        echo -e "[\e[31mError\e[0m] Could not create/update symlink."
        exit
    fi

    echo -e "[\e[32m-\e[0m] Version switched to: \e[33m${VERSION}\e[0m"
}

function list() {

    CURRENT=$(basename $(readlink -f ${TARGET}))

    echo -e "\e[1m\e[32mListing available symlink targets:\e[0m"

    local i=1
    for ver in $(ls ${SOURCE_BASE}) ; do

        echo -ne "  \e[1m[$i]\e[0m   $ver"
        if [ "${CURRENT}" == "${ver}" ]; then
            echo -ne " \e[1m\e[34m*\e[0m"
        fi
        echo -ne "\n"

        ((i++))
    done
}

function show() {
    LINK=$(readlink -e ${TARGET})
    if [ -z "${LINK}" ]; then
       echo -e "Symlink \e[1m${TARGET}\e[0m does not exist."
    else :
       echo -e "\e[1m\e[32mCurrent symlink points to:\e[0m"
       echo "  ${LINK}"
    fi
}

function usage() {
    echo "Usage: ${0} [ list | set | show | help ]"
}

function help() {
    echo -e "Manage the \e[1m${TARGET}\e[0m symlink"
    usage
    echo -e "\n\e[1m\e[32mCommands:\e[0m"
    echo -e "  \e[1m\e[34mlist\e[0m\t\t\tList available eoscdt targets (directories in \e[1m${SOURCE_BASE}\e[0m)"
    echo -e "  \e[1m\e[34mset\e[0m <index>\t\tSet a new eoscdt symlink target"
    echo -e "    index\t\t  Target number (from \e[1m\e[34mlist\e[0m action)"
    echo -e "  \e[1m\e[34mshow\e[0m\t\t\tShow what the current symlink (\e[1m${TARGET}\e[0m) points to."
    echo -e "  \e[1m\e[34mhelp\e[0m\t\t\tDisplay help text (this text)"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

case "${1}" in
    "list") list ;;
    "set")
        if [ $# -lt 2 ]; then
            echo "usage: ${0} set <index>"
            exit
        fi
        set_version "${2}"
    ;;
    "show") show ;;
    "help") help ;;
    *)  echo -e "[\e[31mError\e[0m] Unrecognized command: '${1}'"
        usage
        exit 1
    ;;
esac
